spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/test_promocean
    #    url: jdbc:postgresql://localhost:5432/promocean
    username: promocean_user
    #    username: postgres
    password: ssafy

  cloud:
    aws:
      region:
        static: ap-northeast-2
      credentials:
        access-key: AKIAZPWN23S2VGRXRHEN
        secret-key: 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

      s3:
        bucket: promocean-bucket

cloudfront:
  domain: d3qr7nnlhj7oex.cloudfront.net

jwt:
  secret: YWJjZGFic2Rhc2QxMjM0NTY3ODkwYWJjZGVmZ2hpamtsbW5vcA==
  expiration_time: 8670000

# GMS API 설정
gms:
  api:
    key: S13P32A208-5b9a0f32-7743-4e30-8365-75df5b1ab61f
    base-url: https://gms.ssafy.io/gmsapi
    gpt:
      url: ${gms.api.base-url}/api.openai.com/v1/chat/completions
      model: gpt-5
    gemini:
      url: ${gms.api.base-url}/generativelanguage.googleapis.com/v1beta/models/gemini-2.0-flash-exp-image-generation:generateContent

# 로컬 전용 로깅 설정
logging:
  level:
    com.ssafy.a208: DEBUG


server:
  address: 0.0.0.0